trigger:
  - master

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - stage: BuildAndTest
    jobs:
      - job: BuildTestJob
        pool: mypool
        steps:
          # Single Maven task that both builds and runs tests
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              goals: 'verify' # 'verify' runs both package and test

          # Publish test reports
          - task: PublishAllureReport@1
            displayName: 'Publish Report'
            inputs:
              allureVersion: 2.27.0
              testResultsDir: allure-results

          # Copy and publish artifacts
          - task: CopyFiles@2
            inputs:
              contents: '*/target/.jar'
              targetFolder: '$(build.artifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(build.artifactStagingDirectory)'
              artifactName: 'drop'

  - stage: NotifySuccess
    condition: succeeded()
    jobs:
      - job: NotifyJob
        pool: mypool
        steps:
          - script: echo Build was successful!
            displayName: 'Print success message'