trigger:
  - master

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool: mypool
        steps:
          - task: Maven@3
            inputs:
              mavenVersionOption: 'SpecificVersion'
              mavenVersion: '3.9.4'
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: CopyFiles@2
            inputs:
              contents: '**/target/*.jar'
              targetFolder: '$(build.artifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: Test
    jobs:
      - job: TestJob
        pool: mypool
        steps:
          - task: Maven@3
            inputs:
              mavenVersionOption: 'SpecificVersion'
              mavenVersion: '3.9.4'
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'test'

  - stage: NotifySuccess
    condition: succeeded()
    jobs:
      - job: NotifyJob
        pool: mypool
        steps:
          - script: echo Build was successful!
            displayName: 'Print success message'
